import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "@styles/globals.css";
import RootLayoutWrapper from "@/components/layouts/root-layout";
import SplashGate from "@/components/layouts/splash-gate";
import { env } from "@/env";
import { cn } from "@/lib/utils";
import Maintenance from "./maintenance";
import { DebugInfo } from "@/components/debug-info";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const isMaintenance = env.IS_MAINTENANCE === "true";
const isDevelopment = env.NODE_ENV === "development";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        "dark",
        geistSans.variable,
        geistMono.variable,
        "font-mono",
        jetbrainsMono.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        {isMaintenance ? (
          <Maintenance />
        ) : (
          <SplashGate>
            <RootLayoutWrapper>{children}</RootLayoutWrapper>
          </SplashGate>
        )}
        <DebugInfo enabled={isDevelopment} />
      </body>
    </html>
  );
}
